name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write # Aumentado a write para asegurar que se pueda crear la rama gh-pages si es necesario
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create .env.production file with API key
        run: |
          if [ -z "${{ secrets.GEMINI_API_KEY }}" ]; then
            echo "Error: GEMINI_API_KEY no está configurado en los secretos de GitHub."
            echo "Por favor, configúralo en la configuración del repositorio en GitHub -> Settings -> Secrets and variables -> Actions -> New repository secret"
            exit 1
          fi
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env.production

      - name: Build
        run: npm run build

      - name: Add .nojekyll file
        run: touch ./dist/.nojekyll
        
      - name: Verificar archivos PWA
        run: |
          echo "Verificando archivos PWA generados..."
          
          # Comprobar archivos esenciales de PWA
          for file in manifest.webmanifest sw.js; do
            if [ -f "./dist/$file" ]; then
              echo "✅ $file encontrado"
            else
              echo "⚠️ $file no encontrado"
            fi
          done
          
          # Verificar iconos SVG
          if [ -d "./dist/icons" ] || [ -d "./dist/assets/icons" ]; then
            echo "✅ Directorio de iconos encontrado"
            ls -la ./dist/icons || ls -la ./dist/assets/icons
          else
            echo "⚠️ Directorio de iconos no encontrado. Copiando iconos manualmente..."
            mkdir -p ./dist/icons
            cp -r ./public/icons/*.svg ./dist/icons/
          fi

      # Verificar estructura del directorio dist
      - name: Verificar estructura del directorio dist
        run: |
          echo "Contenido del directorio dist:"
          ls -la ./dist
          echo "Tamaño del directorio dist:"
          du -sh ./dist
      
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
